package ch.fhnw.crm.exchangeWebservice.data.domain;

import java.sql.Date;
import java.time.LocalDate;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;

import io.swagger.v3.oas.annotations.Hidden;
import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotEmpty;
import ch.fhnw.crm.exchangeWebservice.data.domain.*;

// declaring a database relation item (the item to be exchanged)
// @Table is used to specify the name of the table in the database

	// save new item
@Entity
@Table(name = "items")
public class Item {

	// defining the primary key value that will be automatically generated by the database


    @Id
	@GeneratedValue
	@Hidden
	private Long itemId;

	@NotEmpty(message = "Please provide a title for your item")
	private String itemTitle;

	@NotEmpty(message ="Please provide a description for your item")
	@Column(length = 1000)
	private String itemDescription;

	// @Temproal is used to specify the date format

	@Column(name ="ItemListingDate")
	@Temporal(TemporalType.DATE)
	private Date itemListingDate;

	@Enumerated(EnumType.STRING)
	private ItemStatus itemStatus;

	@ManyToOne
	@JoinColumn(name = "categoryId", nullable = false)
	private ItemCategory itemCategory;

	// one item belongs to one user
	@ManyToOne
	@JoinColumn(name = "userId")
	private User user;

	// one item can have one transaction
	
	@OneToOne
	@JoinColumn(name = "transactionId")
	private Transaction transaction;

	//constructors, getters and setters

	public Long getItemId() {
		return itemId;
	}

	public void setItemId(Long itemId) {
	  this.itemId = itemId;
	}

	public String getItemTitle() {
		return itemTitle;
	}

	public void setItemTitle(String itemTitle) {
		this.itemTitle = itemTitle;
	}

	public String getItemDescription() {
		return itemDescription;
	}

	public void setDescription(String itemDescription) {
		this.itemDescription = itemDescription;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user){
	this.user = user;
	}

	public Date getItemListingDate() {
		return itemListingDate;
	}

	public void setItemListingDate(Date itemListingDate) {
		this.itemListingDate = itemListingDate;
	}

	public ItemStatus getItemStatus() {
		return itemStatus;
	}

	public void setItemStatus(ItemStatus itemStatus) {
		this.itemStatus = itemStatus;
	}

	public ItemCategory getItemCategory() {
		return itemCategory;
	}

	public void setItemCategory(ItemCategory itemCategory) {
		this.itemCategory = itemCategory;
	}

	public Transaction getTransaction() {
		return transaction;
	}

	public void setTransaction(Transaction transaction) {
		this.transaction = transaction;
	}

}

	
